name: Deployment (Azure Web App)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Debug

      - name: dotnet publish
        run: dotnet publish -c Debug -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: 'carefusion'
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: 'carefusion'
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'carefusion'
          package: .
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DB_STRING_GH: ${{ secrets.DB_STRING }}

      - name: Enable Swagger in Development
        run: |
          echo "Enabling Swagger for Development"
          # Add any additional steps to ensure Swagger is enabled in your development environment
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "DB_STRING=${{ secrets.DB_STRING }}" >> $GITHUB_ENV


